version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: . # location of dockerfile
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=edward
      - MONGO_PASSWORD=password
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edward
      - MONGO_INITDB_ROOT_PASSWORD=password