version: "3"
services:
  nginx:
    ports:
      - "80:80"
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2 # number of container to update at a time
        delay: 15s
    build:
      context: . # location of dockerfile
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=edward
      - MONGO_PASSWORD=password
    command: node index.js
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edward
      - MONGO_INITDB_ROOT_PASSWORD=password