version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro # bind mount nginx files
  node-app:
    build: .
    image: edwj03/ytnotes
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=edward
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db # named volume - name:path
  redis:
    image: redis:latest

# need to do this for named volumes since can be used across multiple services
volumes:
  mongo-db: 