apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 3000 # has to match container port!
      nodePort: 30007
